# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        
    - run: npm install
    - run: npm run test
    - run: npm run build

    - name: Docker Login
      run: docker build -t ${{ vars.REGISTRY_URL }}/cicd:0.0.1 .

    - name: Docker Login
      run: docker login ${{ vars.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_TOKEN }}

    - name: Docker Push
      run: docker push ${{ vars.REGISTRY_URL }}/cicd:0.0.1

  deploy:

    needs: build

    runs-on: : ubuntu-vm-node

    steps:
      - name: Docker Login
        run: ssh server docker login ${{ vars.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_TOKEN }}

      - name: Docker Pull
        run: ssh server docker pull ${{ vars.REGISTRY_URL }}/cicd:0.0.1

      - name: Docker Stop Old Container
        run: ssh server docker stop cicd-server
        continue-on-error: true

      - name: Docker Remove Old Container
        run: ssh server docker rm cicd-server
        continue-on-error: true

      - name: Docker Run container
        run: ssh server docker run -d --restart unless-stopped --name cicd-server -p 3000:3000 ${{ vars.REGISTRY_URL }}/cicd:0.0.1